### ISSUE TITLE
Service name AdvancedMobileAccess will be changed soon

### ISSUE THREAD

**Issue by tfrank64** [IBM/BluePic#404]
In the command `bx service create AdvancedMobileAccess "Graduated tier" "BluePic-App-ID"`
AdvancedMobileAccess will be changed soon to AppID, just want to document this here. The services.sh, manifest.yml, and cloud_config.json files will need to be changed.

**Comment by ljbennett62** [comment]
Thank you Taylor - what is the timeline on that change?

**Comment by tfrank64** [comment]
Not sure, exactly. In talking with @vitalymibm there should be an official notification and/or banner in Bluemix when this happens.

**Comment by hongjs-ibm** [comment]
Hi, AdvancedMobileAccess service was not created in the DevOps Toolchain also.

![image](https://user-images.githubusercontent.com/26399212/28455335-affe39c8-6e39-11e7-9c2d-45e43d0b9e44.png)

I think the Mobile Client Access service (known as AdvancedMobileAccess) was replaced with App ID. Please visit this page. https://console.bluemix.net/docs/services/mobileaccess/index.html

**Comment by vitalymibm** [comment]
@tfrank64 @hongjsk 
The service was renamed on Jul 5, so everything should be updated according to the new name AppID.

**Comment by tfrank64** [comment]
@ljbennett62

**Comment by ljbennett62** [comment]
@tfrank64 - will do
