### ISSUE TITLE
project ID - where do i find it

### ISSUE THREAD

**Issue by flangel** [IBM/BluePic#410]
The documentation mentions a project id. Where on Bluemix do i find this project ID? Where is it?

**Comment by tfrank64** [comment]
If you run the following command with the Bluemix CLI, `bx app env <Your_BluePic_Name>`, then you will see all the credentials for your application (assuming it was setup correctly). From here, you can find `projectId` under the Object Storage service. I assume that is the projectId you are wanting.

**Comment by flangel** [comment]
thank you
